---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      if  [[ -f post_build.sh ]]; then
        chmod +x post_build.sh;
        echo "executing the post_build script";
        sh post_build.sh;
      else
        echo "the post_build script does not exist";
      fi
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
      api_key: ${API_KEY}
    script: |-
      #!/bin/bash
      cf create-service "alert-label" "alert-plan" "alert-name"
      cf create-service "auth-label" "auth-plan" "auth-name"
      cf create-service "compose-for-mongodb" "Standard" "my-mongodb"
      cf create-service "compose-for-postgresql" "Standard" "my-postgresql"
      cf push "${CF_APP}"
      # cf logs "${CF_APP}" --recent
