// The content of this file was generated by IBM Cloud
// No not modify it as it might get overridden

var IBMCloudEnv = require('ibm-cloud-env');
var serviceManager = require('./service-manager');
IBMCloudEnv.init();

module.exports = function(app){
	require('./service-alert-notification')(app, serviceManager);
	require('./service-appid')(app, serviceManager);
	require('./service-mongodb')(app, serviceManager);
	require('./service-postgre')(app, serviceManager);

};